import React from "react";
import HeroImage from "../components/common/headerImage";
import Header from "../components/layout/header";
import Head from "next/head";
import Accordion from "../components/common/accordion";
import { FAQContent } from "../constants/faq";

export default function IndustryCompass() {
  return (
    <div className="bg-white overflow-scroll no-scrollbar h-screen">
      <Head>
        <title>Industry Compass-Srisudha Consultancy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <HeroImage title="Industry Compass" subtitle="Home - Industry Compass" />
      <div className="max-w-1200 mx-auto">
        <div className="flex items-center py-14  flex-col gap-2">
          <p className="text-3xl uppercase font-Poppins font-semibold">
            <span className="text-[#9401D9]">Industry </span>
            <span>Compass</span>
          </p>
          <div className="flex w-full justify-center">
            <span className="bg-[#207eff] w-[15%] h-1" />
            <span className="bg-[#4f6592] w-[15%] h-1" />
          </div>
          <h2 className="mt-2 font-light text-center text-gray-600">
            Srisudha Consultancy Services offers expert guidance across a wide
            range of industries, empowering businesses with tailored financial,
            tax, business, and legal solutions to navigate their unique
            challenges and achieve success.
          </h2>
        </div>
        <div className="eduvibe-tabs-title">
          <div
            className="lg:flex sm:block  gap-3 items-center justify-center"
            data-te-toggle="pill"
            data-te-target="#tabs-home1"
            href="#tabs-home1"
            data-te-nav-active
            id="tabs-home1"
            role="tabpanel"
            aria-labelledby="tabs-home-tab1"
            aria-controls="tabs-home1"
            aria-selected="true"
          >
            <div className="w-full  px-4  mt-5">
              <div className="p-4  rounded-lg   mt-5 mb-10 grid  gap-20 gap-y-4">
                {FAQContent?.map((value, index) => (
                  <Accordion
                    answer={value?.value}
                    title={`${index + 1}.  ${value?.label}`}
                  />
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
