import Head from "next/head";
import React from "react";
import Header from "../components/layout/header";
import HeroImage from "../components/common/headerImage";
import CustomBorder from "../components/common/border";
import { SerivcesOverView, ServicesConstant } from "../constants/services";
import CompanyList from "../components/common/companies";
import Image from "next/image";
import { FaArrowRight } from "react-icons/fa6";

export default function Services() {
  return (
    <div className="bg-white overflow-scroll no-scrollbar h-screen">
      <Head>
        <title>Home-Srisudha Consultancy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <HeroImage title="Services" subtitle="Home - Services" />
      <section className=" mx-auto max-w-1200  py-8 xl:py-20">
        <div>
          <div className="grid px-6 xl:px-10 mt-4 md:grid-cols-2 gap-6 lg:gap-10">
            <div>
              <div className="flex gap-4 text-primary items-center">
                <CustomBorder />
                <p>Services</p>
              </div>
              <h2 className=" text-[28px] xl:text-[38px] text-black font-bold leading-[36px] xl:leading-[46px] ">
                Comprehensive Business Solutions: Unlock Your Company’s
                Potential with Srisudha Consultancy Services
              </h2>
            </div>
            <div>
              <div>
                <div className="text-center text-gray-500  justify-center flex items-center">
                  <svg
                    aria-hidden="true"
                    viewBox="0 0 448 512"
                    className="h-8 w-8  e-font-icon-svg e-fas-building text-gray-600"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="currentColor"
                  >
                    <path d="M436 480h-20V24c0-13.255-10.745-24-24-24H56C42.745 0 32 10.745 32 24v456H12c-6.627 0-12 5.373-12 12v20h448v-20c0-6.627-5.373-12-12-12zM128 76c0-6.627 5.373-12 12-12h40c6.627 0 12 5.373 12 12v40c0 6.627-5.373 12-12 12h-40c-6.627 0-12-5.373-12-12V76zm0 96c0-6.627 5.373-12 12-12h40c6.627 0 12 5.373 12 12v40c0 6.627-5.373 12-12 12h-40c-6.627 0-12-5.373-12-12v-40zm52 148h-40c-6.627 0-12-5.373-12-12v-40c0-6.627 5.373-12 12-12h40c6.627 0 12 5.373 12 12v40c0 6.627-5.373 12-12 12zm76 160h-64v-84c0-6.627 5.373-12 12-12h40c6.627 0 12 5.373 12 12v84zm64-172c0 6.627-5.373 12-12 12h-40c-6.627 0-12-5.373-12-12v-40c0-6.627 5.373-12 12-12h40c6.627 0 12 5.373 12 12v40zm0-96c0 6.627-5.373 12-12 12h-40c-6.627 0-12-5.373-12-12v-40c0-6.627 5.373-12 12-12h40c6.627 0 12 5.373 12 12v40zm0-96c0 6.627-5.373 12-12 12h-40c-6.627 0-12-5.373-12-12V76c0-6.627 5.373-12 12-12h40c6.627 0 12 5.373 12 12v40z"></path>
                  </svg>
                </div>

                <p className="text-[32px] mt-1 text-gray-600 text-center font-bold leading-[46px] ">
                  At Srisudha Consultancy
                </p>
              </div>
              <h3 className="text-gray-500 mt-2 text-justify xl:text-start font-normal font-Nunito  leading-8 text-base ">
                We provide an extensive range of services to cater to your
                business needs, with a team of experienced Chartered Accountants
                and Cost Accountants on board. We take pride in offering
                customized solutions, ensuring that your business thrives in the
                dynamic market. Our services encompass financial management,
                business strategy, tax planning, regulatory compliance, and
                more. By partnering with us, you can unlock the full potential
                of your business and achieve unparalleled growth. Trust Srisudha
                Consultancy to guide you towards a successful and sustainable
                future.
              </h3>
            </div>
          </div>
        </div>
      </section>
      <section className="xl:max-w-[1232px] flex flex-row overflow-scroll no-scrollbar mx-auto px-4 md:grid py-12 pt-16 md:py-20 grid-cols-1 md:grid-cols-3 gap-8  ">
        {SerivcesOverView.map((value) => (
          <CourseOverViewCard value={value} />
        ))}
      </section>
      <section className="max-w-[1232px]  mx-auto px-4 pb-12 md:pb-16 grid py-8 grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8 gap-y-10  ">
        {ServicesConstant.map((value) => (
          <ServiceCard value={value} />
        ))}
      </section>
      <CompanyList />
    </div>
  );
}

function CourseOverViewCard({ value }) {
  return (
    <div className="testiCardHover w-full sm:w-1/2 md:w-full flex-shrink-0 relative flex group hover:bg-[url('/home/cover/cover3.jpeg')]    cursor-pointer  flex-col items-center px-8 pb-8">
      <div className="-mt-14 relative z-30 flex flex-col items-center">
        <div className="p-4 bg-gray-100 group-hover:bg-black  rounded-full">
          <div className="bg-white w-24 flex items-center justify-center h-24 rounded-full">
            <i className={`${value.icon} text-primary text-5xl`}></i>
          </div>
        </div>
        <p className="mt-6 text-primaryText group-hover:text-gray-100 font-semibold text-xl text-center">
          {value.label}
        </p>
        <p className="mt-4 text-center font-light group-hover:text-gray-300 ">
          {value.description}
        </p>
        <button className="px-4 group-hover:bg-primary group-hover:text-black py-1.5 mt-6 bg-black text-white text-sm">
          Read more
        </button>
      </div>
      <div className="absolute hidden group-hover:block group-hover:bg-black inset-0 group-hover:bg-opacity-90 " />
    </div>
  );
}

function ServiceCard({ value }) {
  return (
    <div className="hover:testiCardHover hover:-translate-y-4 relative flex group   cursor-pointer flex-col items-center p-3 py-6 transition-all duration-300">
      <div className="w-full rounded-md overflow-hidden h-40 relative">
        <Image
          src={`/service/${value.image}`}
          layout="fill"
          objectFit="cover"
        />
      </div>
      <div className="relative z-30 flex-1 flex flex-col items-center">
        <p className="mt-6 max-w-72 text-primary  font-semibold text-xl text-center">
          {value.label}
        </p>
        <p className="mt-4 flex-1 text-center font-light  ">
          {value.description}
        </p>
        <div className="flex items-center group mt-8">
          <button className="px-4 text-black group-hover:text-white transition-all duration-300 font-semibold self-stretch relative  py-1.5    text-sm">
            <div className="absolute flex flex-row-reverse top-0 bottom-0 left-full right-0 group-hover:bg-black group-hover:left-0 transition-all duration-300 "></div>
            <span className="group-hover:text-white relative z-20">
              Read more
            </span>
          </button>
          <div className="bg-primary text-white p-2.5">
            <FaArrowRight className="h-3.5 w-3.5" />
          </div>
        </div>
      </div>
    </div>
  );
}
