import React from "react";
import Header from "../components/layout/header";
import Image from "next/image";
import Head from "next/head";
import { teams } from "../constants/team";
import CustomBorder from "../components/common/border";
import HeroImage from "../components/common/headerImage";

export default function Team() {
  return (
    <div className="bg-white overflow-scroll no-scrollbar h-screen">
      <Head>
        <title>Home-Srisudha Consultancy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <HeroImage />
      <div className="py-20 grid grid-cols-3 gap-8 mx-auto max-w-monitor">
        <div>
          <div className="flex gap-4 text-primary items-center">
            <CustomBorder />
            <p>Team Member</p>
          </div>
          <div className="flex gap-4 mt-4">
            <div className="flex-shrink-0 mt-2 flex flex-col gap-1 ">
              <div className="grid grid-cols-3 gap-1">
                {[
                  { color: "bg-black" },
                  { color: "bg-primary" },
                  { color: "bg-black" },
                ].map((value) => (
                  <p
                    className={`h-2.5 aspect-square rounded-full ${value.color}`}
                  />
                ))}
              </div>
              <div className="grid grid-cols-3 gap-1">
                {[
                  { color: "bg-white" },
                  { color: "bg-black" },
                  { color: "bg-black" },
                ].map((value) => (
                  <p
                    className={`h-2.5 aspect-square rounded-full ${value.color}`}
                  />
                ))}
              </div>
              <div className="grid grid-cols-3 gap-1">
                {[
                  { color: "bg-white" },
                  { color: "bg-white" },
                  { color: "bg-primary" },
                ].map((value) => (
                  <p
                    className={`h-2.5 aspect-square rounded-full ${value.color}`}
                  />
                ))}
              </div>
            </div>
            <h2 className="text-[40px] text-black font-bold leading-[46px] ">
              We always work with a great team.
            </h2>
          </div>
        </div>
        <div className="grid grid-cols-2 gap-6 col-span-2">
          {teams.slice(0, 2).map((value) => (
            <div className=" flex group cursor-pointer   flex-col items-center gap-3">
              <div className="w-full aspect-square relative">
                <Image
                  src={`/team/${value.image}`}
                  layout="fill"
                  objectFit="cover"
                />
                <div className="inset-0  transition-all duration-200 absolute hidden group-hover:block  ">
                  <Image
                    src={"/team/overlay.png"}
                    layout="fill"
                    objectFit="cover"
                  />
                </div>
                <div className="hidden left-0 transition-all duration-200 text-[#f2f2f2] right-0 text-sm   px-8 text-center group-hover:block py-6 absolute bottom-4 ">
                  {value.description}
                </div>
              </div>
              <div>
                <h3 className="text-center font-bold text-xl">{value.name}</h3>
                <h4 className="text-center text-gray-400 text-[15px] font-light">
                  {value.designation}
                </h4>
              </div>
            </div>
          ))}
        </div>
      </div>
      <section className="grid pt-6 pb-10 mx-auto max-w-monitor grid-cols-4 gap-y-14 gap-10">
        {teams.slice(2).map((value) => (
          <div className="flex flex-col group cursor-pointer items-center py-10 hover:teamShadow transition-all duration-300">
            <div className="relative group-hover:shadow-lg w-20 aspect-square rounded-full overflow-hidden">
              <Image
                src={`/team/${value.image}`}
                layout="fill"
                objectFit="cover"
              />
            </div>
            <div className="mt-4 text-center">
              <h3 className="font-bold ">{value.name}</h3>
              <h4 className="text-gray-500  text-[14px]">
                {value.designation}
              </h4>
              <div className="px-4 hover:bg-primary rounded-sm hover:text-gray-600 hover:font-bold  py-1 bg-blue-50 mt-4 text-sm font-semibold font-Roboto text-gray-600">
                <h4>{value.sublabel}</h4>
              </div>
            </div>
          </div>
        ))}
      </section>
    </div>
  );
}
